name: Build and Release Escript

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'
            
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
          # This step checks out a copy of your repository.
            - name: Checkout the code
              uses: actions/checkout@v4
              
            - name: Set up Erlang and Elixir
              uses: erlef/setup-beam@v1
              with:
                otp-version: "latest"
                elixir-version: "latest"
                install-hex: true
                install-rebar: true

            - name: Install Dependencies
              run: |
                mix local.hex
                mix local.rebar
                mix deps.get
            
            - name: Build
              run: mix escript.build
                
            - name: Test the binary
              run: ./tl -v --help

            - name: Create Github Release
              id: create_release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: ./tl